name: CeleroCustomLayer
services:
  ms-transaction:
    build:
      context: ./ms-transaction
      target: dev
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  ms-process:
    build:
      context: ./ms-process
      target: dev
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  ms-logger:
    build:
      context: ./ms-logger
      target: dev
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3.13.6-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - default
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15.9-alpine
    ports:
      - 5432:5432
    networks:
      - default
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
