name: CeleroCustomLayer
services:
  ms-transaction:
    build:
      context: ./ms-transaction
      target: dev
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    restart: on-failure
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    depends_on:
      rabbitmq:
        condition: service_healthy

  ms-process:
    build:
      context: ./ms-process
      target: dev
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3.13.6-management-alpine
    ports:
      - 15673:15672
    networks:
      - default
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5