# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import setup_pb2 as setup__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in setup_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SetupStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddAccount = channel.unary_unary(
                '/setup.Setup/AddAccount',
                request_serializer=setup__pb2.AddAccountRequest.SerializeToString,
                response_deserializer=setup__pb2.AddAccountResponse.FromString,
                _registered_method=True)


class SetupServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SetupServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAccount,
                    request_deserializer=setup__pb2.AddAccountRequest.FromString,
                    response_serializer=setup__pb2.AddAccountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'setup.Setup', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('setup.Setup', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Setup(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/setup.Setup/AddAccount',
            setup__pb2.AddAccountRequest.SerializeToString,
            setup__pb2.AddAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
