# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: setup.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'setup.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsetup.proto\x12\x05setup\"\x1d\n\x0bTransaction\x12\x0e\n\x06trx_id\x18\x01 \x01(\t\"Z\n\x07\x41\x63\x63ount\x12\x0e\n\x06\x62ranch\x18\x01 \x01(\t\x12\x15\n\raccountnumber\x18\x02 \x01(\t\x12\x13\n\x0b\x61\x63\x63ounttype\x18\x03 \x01(\t\x12\x13\n\x0bopeningdate\x18\x04 \x01(\t\"4\n\x11\x41\x64\x64\x41\x63\x63ountRequest\x12\x1f\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x0e.setup.Account\"=\n\x12\x41\x64\x64\x41\x63\x63ountResponse\x12\'\n\x0btransaction\x18\x01 \x01(\x0b\x32\x12.setup.Transaction2J\n\x05Setup\x12\x41\n\nAddAccount\x12\x18.setup.AddAccountRequest\x1a\x19.setup.AddAccountResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'setup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTION']._serialized_start=22
  _globals['_TRANSACTION']._serialized_end=51
  _globals['_ACCOUNT']._serialized_start=53
  _globals['_ACCOUNT']._serialized_end=143
  _globals['_ADDACCOUNTREQUEST']._serialized_start=145
  _globals['_ADDACCOUNTREQUEST']._serialized_end=197
  _globals['_ADDACCOUNTRESPONSE']._serialized_start=199
  _globals['_ADDACCOUNTRESPONSE']._serialized_end=260
  _globals['_SETUP']._serialized_start=262
  _globals['_SETUP']._serialized_end=336
# @@protoc_insertion_point(module_scope)
